name: mfcc_bee
description: A starting libraries of extract mfcc_bees.
version: 1.0.1
homepage: https://github.com/certainlyWrong/mfcc_bee

environment:
  sdk: '>=2.17.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  args: ^2.3.1
  csv: ^5.0.1
  fftea: ^1.1.1
  scidart: ^0.0.2-dev.9
  wav: ^1.1.0
